### ISSUE TITLE
[BUG]download doesn't work

### ISSUE THREAD

**Issue by foolstuck** [FayasNoushad/Youtube-Video-Thumbnail#15]
my code is as follow

link = 'some-youtube-link'

ytthumb.download_thumbnail(video=link)

error message:\
UnboundLocalError: cannot access local variable 'thumbnail' where it is not associated with a value

**Comment by FayasNoushad** [comment]
Fixed

https://github.com/FayasNoushad/Youtube-Video-Thumbnail/releases/tag/v1.4.7
